env:
  global:
    - CONAN_UPLOAD=1
    - CONAN_REFERENCE="hwloc/1.11.5"
    - CONAN_USERNAME="selenorks"
    - CONAN_CHANNEL="testing"
    - CONAN_TOTAL_PAGES=1
    - CONAN_CURRENT_PAGE=1

matrix:
    include:
        - os: linux
          dist: trusty
          env: CONAN_GCC_VERSIONS=4.8 CONAN_USE_DOCKER=1
          services:
            - docker
          sudo: required
          language: cpp

        - os: osx
          osx_image: xcode7.1 # apple-clang 7.0
          language: generic
          env: CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=1

        - os: osx
          osx_image: xcode7.1 # apple-clang 7.0
          language: generic
          env: CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=2
          
        - os: osx
          osx_image: xcode7.1 # apple-clang 7.0
          language: generic
          env: CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=3
          
        - os: osx
          osx_image: xcode7.1 # apple-clang 7.0
          language: generic
          env: CONAN_TOTAL_PAGES=4 CONAN_CURRENT_PAGE=4

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh

