notifications:
  email: false

sudo: required
python: 3.4
language: cpp
matrix:
    include:
        - os: linux
          dist: precise
        - os: osx
          env: COMPILER=clang++
         
install:
- bash -x install.sh

script:
- python build.py
