notifications:
  email: false

env:
  global:
    - CONAN_UPLOAD=1
    - CONAN_REFERENCE="hwloc/1.11.5"
    - CONAN_USERNAME="selenorks"
    - CONAN_CHANNEL="testing"
    - CONAN_TOTAL_PAGES=1
    - CONAN_CURRENT_PAGE=1

matrix:
    include:
        - os: osx
          osx_image: xcode6.4 # apple-clang 6.1
          language: generic
          env: COMPILER=clang++
         
install:
  - ./.travis/install.sh

script:
  - ./.travis/run.sh
