notifications:
  email: false

env:
  global:
    - CONAN_UPLOAD=1
    - CONAN_REFERENCE="hwloc/1.11.5"
    - CONAN_USERNAME="selenorks"
    - CONAN_CHANNEL="testing"
    - CONAN_TOTAL_PAGES=1
    - CONAN_CURRENT_PAGE=1

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    #packages:
    #- gcc-4.8
    #- g++-4.8
    #- clang
    #- libxml2-dev
    #- libxml2-dev:i386
    #- libudev0
    #- libudev0:i386

matrix:
    include:
        - os: linux
          dist: trusty
          env: CONAN_GCC_VERSIONS=4.6 CONAN_USE_DOCKER=1
          services:
            - docker
          sudo: required
          language: cpp

        - os: osx
          osx_image: xcode6.4 # apple-clang 6.1
          language: generic
          env: COMPILER=clang++
         
install:
  - ./.travis/install.sh

script:
  - ./.travis/run.sh
